# disable in production:
local_backend: true
# command to run a local Decap instance: npx-decap-server
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de, es, ar]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: de

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/upload"
public_folder: "/"

site_url: https://legalisierungjetzt.netlify.app/

media_library:
  name: cloudinary
  # output_filename_only: true
  config:
    cloud_name: <YOUR_CLOUD_NAME_HERE>
    api_key: <YOUR_API_KEY_HERE>

# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  i18n: true
  fields:
    - {
        name: "metaTitle",
        label: "SEO Title",
        widget: "string",
        default: "{{ title }}",
        required: true,
        i18n: duplicate,
      }
    - {
        name: "metaDescription",
        label: "SEO Description",
        widget: "string",
        pattern: [".{20,160}", "between 20 and 160 characters"],
        required: true,
        hint: "must be between 20 and 160 characters",
        i18n: duplicate,
      }
    - {
        name: "metaImage",
        label: "SEO image",
        widget: "image",
        i18n: duplicate,
      }
    - {
        name: "keywords",
        label: "keywords",
        widget: "string",
        hint: "keywords are comma seperated",
        required: false,
        i18n: duplicate,
      }

collections:
  - name: "globalContent"
    label: "Global content"
    i18n:
      structure: single_file
    files:
      - name: "header"
        label: "Header"
        i18n: true
        file: "content/header.md"
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
          - {
              name: "content",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
      - name: "footer"
        label: "Footer"
        file: "content/footer.md"
        i18n: true
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
          - {
              name: "content",
              label: "Content",
              widget: "markdown",
              i18n: duplicate,
            }
          - { name: "title2", label: "Title 2", widget: "string", i18n: true }
          - {
              name: "content2",
              label: "Content 2",
              widget: "markdown",
              i18n: duplicate,
            }
          - { name: "title3", label: "Title 3", widget: "string", i18n: true }
          - {
              name: "content3",
              label: "Content 3",
              widget: "markdown",
              i18n: true,
            }
      - label: "paths"
        name: "paths"
        i18n: true
        file: "content/paths.md"
        fields:
          - label: "Letter"
            name: "letter"
            i18n: duplicate
            required: false
            widget: "boolean"
          - label: "Events"
            name: "events"
            i18n: duplicate
            required: false
            widget: "boolean"
          - label: "Press"
            name: "press"
            i18n: duplicate
            required: false
            widget: "boolean"
          - label: "Documents"
            name: "documents"
            i18n: duplicate
            widget: "boolean"
            required: false

  # SINGLE PAGES
  - name: "pages"
    label: "Pages"
    i18n:
      structure: single_file
    files:
      - name: "home"
        label: "Home"
        i18n: true
        file: "content/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
          - {
              name: "content",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
          - *seo
      - name: "letter"
        label: "Letter"
        i18n: true
        file: "content/letter.md"
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
          - {
              name: "content",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
      - name: "events"
        label: "Events"
        i18n: true
        file: "content/events.md"
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
          - {
              name: "subTitle1",
              label: "subtitle 1",
              widget: "string",
              i18n: true,
              default: "fields.title",
            }
          - {
              name: "content1",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
          - {
              name: "subTitle2",
              label: "subtitle 2",
              widget: "string",
              i18n: true,
              default: "fields.title",
            }
          - {
              name: "content2",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
      - name: "press"
        label: "Press"
        i18n: true
        file: "content/press.md"
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
          - {
              name: "subTitle1",
              label: "sub-title1",
              widget: "string",
              i18n: true,
              default: "fields.title",
            }
          - {
              name: "content1",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
          - {
              name: "subTitle2",
              label: "subtitle 2",
              widget: "string",
              i18n: true,
              default: "fields.title",
            }
          - {
              name: "content2",
              label: "Content",
              widget: "markdown",
              i18n: true,
            }
      - name: "documents"
        label: "Documents"
        i18n: true
        file: "content/documents.md"
        fields:
          - { name: "title", label: "Title", widget: "string", i18n: true }
      - name: "gallery"
        label: "Gallery"
        i18n: true
        file: "content/gallery.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
