# disable in production:
local_backend: true
# command to run a local Decap instance: npx-decap-server
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: "public/upload"
public_folder: "/"

site_url: https://legalisierungjetzt.netlify.app/

media_library:
  name: cloudinary
  # output_filename_only: true
  config:
    cloud_name: <YOUR_CLOUD_NAME_HERE>
    api_key: <YOUR_API_KEY_HERE>

# SEO anchor:
seo: &seo
  name: "SEOmetaData"
  label: "SEO"
  widget: "object"
  collapsed: true
  fields:
    - {
        name: "metaTitle",
        label: "SEO Title",
        widget: "string",
        default: "{{ title }}",
        required: true,
      }
    - {
        name: "metaDescription",
        label: "SEO Description",
        widget: "string",
        pattern: [".{20,160}", "between 20 and 160 characters"],
        required: true,
        hint: "must be between 20 and 160 characters",
      }
    - { name: "metaImage", label: "SEO image", widget: "image" }
    - {
        name: "keywords",
        label: "keywords",
        widget: "string",
        hint: "keywords are comma seperated",
        required: false,
      }

collections:
  - name: "globalContent"
    label: "Global content"
    i18n: true
    files:
      - name: "header"
        label: "Header"
        file: "content/pages/header.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
      - name: "footer"
        label: "Footer"
        file: "content/pages/footer.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
      - label: "buttons"
        name: "buttons"
        file: "content/site/buttons.md"
        fields:
          - label: "next"
            name: "next"
            widget: "string"
          - label: "previous"
            name: "previous"
            widget: "string"
          - label: "close"
            name: "close"
            widget: "string"
          - label: "article: more"
            name: "article"
            widget: "string"
            default: "read more"
          - label: "form: send"
            name: "send"
            widget: "string"

  # SINGLE PAGES
  - name: "pages"
    label: "Pages"
    i18n: true
    files:
      - name: "home"
        label: "Home"
        i18n: true
        file: "content/pages/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
          - *seo
      - name: "letter"
        label: "Letter"
        file: "content/pages/letter.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "content", label: "Content", widget: "markdown" }
      - name: "events"
        label: "Events"
        extension: json
        file: "content/pages/events.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - {
              name: "subTitle1",
              label: "subtitle 1",
              widget: "string",
              default: "fields.title",
            }
          - { name: "content1", label: "Content", widget: "markdown" }
          - {
              name: "subTitle2",
              label: "subtitle 2",
              widget: "string",
              default: "fields.title",
            }
          - { name: "content2", label: "Content", widget: "markdown" }
      - name: "press"
        label: "Press"
        extension: json
        file: "content/pages/press.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - {
              name: "subTitle1",
              label: "sub-title1",
              widget: "string",
              default: "fields.title",
            }
          - { name: "content1", label: "Content", widget: "markdown" }
          - {
              name: "subTitle2",
              label: "subtitle 2",
              widget: "string",
              default: "fields.title",
            }
          - { name: "content2", label: "Content", widget: "markdown" }
      - name: "documents"
        label: "Documents"
        extension: json
        file: "content/pages/documents.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
      - name: "gallery"
        label: "Gallery"
        extension: json
        file: "content/pages/gallery.json"
        fields:
          - { name: "title", label: "Title", widget: "string" }
